name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Fetch latest precios
        env:
          API_USER: ${{ secrets.API_USER }}
          API_PASS: ${{ secrets.API_PASS }}
          API_URL: https://<TU_DOMINIO>/api/productos
        run: node scripts/fetch-precios.js

      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v3
        with:
          branch: gh-pages
          folder: public
